[application]
default_platform = "fullstack"

[web.app]

# HTML title tag content
title = "open_fair_flow"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
